jobs:
  - name: development
    max_in_flight: 1
    plan:
      - get: dataworks-aws-tarball-adg
        trigger: true
      - get: emr-ami
        trigger: true
      - get: emr-launcher-release
        trigger: true
      - get: s3-data-purger-release
        trigger: true
      - get: analytical-dataset-generation-exporter-release
        trigger: true
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
      - .: (( inject meta.plan.terraform-plan ))
